export enum CreditRole {
  PRODUCER = 'producer',
  EXECUTIVE_PRODUCER = 'executive_producer',
  ENGINEER = 'engineer',
  MIXING_ENGINEER = 'mixing_engineer',
  MASTERING_ENGINEER = 'mastering_engineer',
  SONGWRITER = 'songwriter',
  COMPOSER = 'composer',
  ARRANGER = 'arranger',
  PERFORMER = 'performer',
  FEATURED_ARTIST = 'featured_artist',
  BACKING_VOCALS = 'backing_vocals',
  MUSICIAN = 'musician',
  PHOTOGRAPHER = 'photographer',
  ARTWORK_DESIGNER = 'artwork_designer',
  LINER_NOTES = 'liner_notes',
  A_AND_R = 'a_and_r',
  OTHER = 'other',
}
