export enum LocationType {
  STAGE = "stage",
  VENDOR = "vendor",
  RESTROOM = "restroom",
  MEDICAL = "medical",
  SECURITY = "security",
  ENTRANCE = "entrance",
  EXIT = "exit",
  PARKING = "parking",
  ATM = "atm",
  INFO = "info",
  LOST_FOUND = "lost_found",
  VIP = "vip",
  BACKSTAGE = "backstage",
  MERCHANDISE = "merchandise",
  BAR = "bar",
  FOOD_COURT = "food_court",
}